import type { Metadata } from "next";
import { Geist, Geist_Mono, Khula } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/shared/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const khula = Khula({
  variable: "--font-khula",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${khula.variable} antialiased`}
      >
        <Navbar></Navbar>
        <div className="ml-64">
          {children}
        </div>
      </body>
    </html>
  );
}
